all:
	cp used_wood_bar.png ..
	cp big_used_wood_bar.jpg ..
	cp chickenwire-texture.svg ..
	cp birch_bar.png ..
	cp oldbrick.png ..
	cp styrofoam.png ..

clean:
	rm ../used_wood_bar.png ../big_used_wood_bar.jpg ../chickenwire-texture.svg ../birch_bar.png ../oldbrick.png ../styrofoam.png
