all:
	cp Action*.svg ..
	cp Icon*.svg   ..
	cp Proxy*.svg   ..
	cp Status*.svg   ..
	cp ToolboxBackground.svg ..

clean:
	rm -f ../Action*.svg
	rm -f ../Icon*.svg
	rm -f ../Proxy*.svg
	rm -f ../Status*.svg
	rm -f ../ToolboxBackground.svg

