#MYINCDIR=../../3rdParty/include
MYINCDIR=../../3rdParty/Box2D_v2.0.1/Box2D/Include
MYLIBDIR=../../3rdParty/libs

all:
	g++ -o b2d HelloWorld.cpp -I${MYINCDIR} -L${MYLIBDIR} -lbox2d
	
clean:
	rm -f b2d *~
