include ../Makefile 
SVGSRC=DetonatorBoxActivated.svg DetonatorBoxArmed.svg DetonatorBoxDone.svg DetonatorBoxRinging.svg DetonatorBoxHandle.svg \
       Dynamite.svg DynamiteActive.svg DynamiteRinging.svg DynamiteBoom.svg   

